### ISSUE TITLE
`here_data` adds extraneous slash

### ISSUE THREAD

**Issue by tgerke** [pcctc/croquet#26]
> here_data("data-raw")
✖ The data date directory does not exist: /Users/tgerke/Documents/gh-repos-mskcc/c15-153-ribox/data//2023-03-13
ℹ Path /Users/tgerke/Documents/gh-repos-mskcc/c15-153-ribox/data//2023-03-13/data-raw 

Note the `data//` piece, which causes any calls to this path to fail

**Comment by tgerke** [comment]
A little further digging revealed that this is a result of my `_env.yaml` entry reading
```
path-data: '~/Documents/gh-repos-mskcc/c15-153-ribox/data/'
```
I think `here_data` should be agnostic to whether the user includes a trailing slash in the path sent to it; perhaps a check/removal of trailing slashes to the argument would fix things?

**Comment by ddsjoberg** [comment]
update to use `fs::path()` instead of base R

```r
d> fs::path("C:/Users/SjobergD/GitHub/pcctc/", "another_folder")
#> C:/Users/SjobergD/GitHub/pcctc/another_folder
d> file.path("C:/Users/SjobergD/GitHub/pcctc/", "another_folder")
#> "C:/Users/SjobergD/GitHub/pcctc//another_folder"
```

**Comment by ddsjoberg** [comment]
this function is in the process of being migrated to our internal pkg. it was updated there.
