### ISSUE TITLE
pandoc looking for .csl in the wrong place

### ISSUE THREAD

**Issue by tgerke** [pcctc/croquet#27]
Error reads
```
pandoc: /Users/tgerke/Documents/gh-repos-mskcc/c15-153-ribox/metadata/european-urology.csl: openBinaryFile: does not exist (No such file or directory)
```
create PCCTC project stashes these in `_metadata` (leading underscore).

**Comment by ddsjoberg** [comment]
Thanks! I changed the name of the folder from `metadata` to `_metadata` during dev, and clearly missed this update! 

Updated in PR #24
