### ISSUE TITLE
Improve `set_derived_variable_labels()` functionality with iteratives

### ISSUE THREAD

**Issue by Meghansaha** [pcctc/croquet#34]
Currently, `set_derived_variable_labels()` does not play nice with `purrr` fxs (as to be able to set labels iteratively for multiple data frames with one chunk of code.)

Currently would have to use base methods (for-loops, mapply, etc.) to get code to compile without error. But it is extremely clunky, so not advised.

Example of attempted use with `purrr`'s `map()`:

``` r
# Library Load-in----
library(tidyverse)
library(croquet)

# Data Set-up----
# Say we have multiple individual data frames#
df_dm <- tibble(subject = 1:3,
                race = c("white", "black", "asian"),
                age = c(50,60,70)
)

df_labs <- tibble(subject = 1:3,
                  rbc = 5:7
)

df_sites <- tibble(subject = 1:3,
                   site = c("MSK", "Roswell", "Columbia")
)

# Placed into a list#
lst_datasets <-
  list(
    df_dm,
    df_labs,
    df_sites
  )

# A dataframe with variable labels to be referenced
df_labels <- tribble(
  ~df_name,  ~df_label,                         ~var_name, ~var_label, ~notes,
  "df_dm",    "One line per radomized subject", "subject", "Subject ID", "",
  "df_dm",    "One line per radomized subject", "race",    "Subject Race/Ethnicity", "",
  "df_dm",    "One line per radomized subject", "age",     "Subject age in years", "",
  "df_labs",  "One line per radomized subject", "subject", "Subject ID", "",
  "df_labs",  "One line per radomized subject", "rbc",     "Subject red blood cell count", "",
  "df_sites", "One line per radomized subject", "subject", "Subject ID", "",
  "df_labs",  "One line per radomized subject", "site",    "Study Site", ""
)

# Saving as an excel file as `set_derived_variable_labels()` expects a file path as a string #
# Side Note:: Should this be expanded to include tibbles/dataframes/RDS objects?#
write_csv(df_labels, "df_labels.csv")

# Placing in a `map()` function does not work...#
map(lst_datasets,
    ~ .x |>
      set_derived_variable_labels(
        path = "df_labels.csv", drop = FALSE)
)
#> Error in `map()`:
#> ℹ In index: 1.
#> Caused by error in `set_derived_variable_labels()`:
#> ✖ The data name ".x" does not appear in the derived variables file.
#> ℹ Specify one of "df_dm", "df_labs", and "df_sites"
#> Backtrace:
#>     ▆
#>  1. └─purrr::map(...)
#>  2.   └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
#>  3.     ├─purrr:::with_indexed_errors(...)
#>  4.     │ └─base::withCallingHandlers(...)
#>  5.     ├─purrr:::call_with_cleanup(...)
#>  6.     └─global .f(.x[[i]], ...)
#>  7.       └─croquet::set_derived_variable_labels(.x, path = "df_labels.csv", drop = FALSE)
#>  8.         └─cli::cli_abort(...)
#>  9.           └─rlang::abort(...)

#... Instead, each df has to be done separately #
df_dm |>
  set_derived_variable_labels(
    path = "df_labels.csv", drop = FALSE) |>
  View()

df_labs |>
  set_derived_variable_labels(
    path = "df_labels.csv", drop = FALSE) |>
  View()

df_sites |>
  set_derived_variable_labels(
    path = "df_labels.csv", drop = FALSE) |>
  View()
```

<sup>Created on 2023-07-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by shannonpileggi** [comment]
Hi @Meghansaha thanks for submitting! I think the original concept was that individual curated data sets would be created in separate and modular files, not that many would be created and need label assignment simultaneously. Are your workflows going that direction?

**Comment by Meghansaha** [comment]
@shannonpileggi - Possibly! First use-case I can think of is if I have multiple data sets that need to be pulled and labelled within a single script. For instance, vendor data. Multiple data sources from different companies, with similar variables that need similar labelling across the sets. Of course, this is mainly a "quality of life" suggestion though. the function continues to work fine if a single data frame is set up at a time.

**Comment by ddsjoberg** [comment]
The reason for the error is that the function needs to understand the dataset **name** to be able to subset the file with the labels. In a simple (non-mapping) setting, the name can be identified. In a more complex case like this, you need to use the `df_name` argument. Something like this should work (there are multiple ways to make this work of course).

```r
list(mtcars = mtcars, iris = iris) |> 
  purrr::imap(
    ~set_derived_variable_labels(
      data = .x, 
      df_name = .y, 
      path = "df_labels.csv", 
      drop = FALSE
    )
  )
```

**Comment by ddsjoberg** [comment]
I think the error message would be more clear if include a reference to the `df_name` argument: certainly a place for improved messaging.

```r
#> ✖ The data name ".x" does not appear in the derived variables file.
#> ℹ Specify one of "df_dm", "df_labs", and "df_sites"
```

**Comment by Meghansaha** [comment]
Thank you @ddsjoberg! I always forget about `imap()` !! Will try that out and circle back with @shannonpileggi to see if we'd want to improve the messaging (if that falls under croquet's dev scope)
