### ISSUE TITLE
More user friendly output for `add_labelled_sheet()`

### ISSUE THREAD

**Issue by vkatti** [pcctc/croquet#6]
This is in continuation to the discussion [here](https://github.com/shannonpileggi/pipinghotdata_distill/discussions/40#discussioncomment-3702810) on Shanon's blog to provide more user-friendly output for `add_labelled_sheet()`.

The idea is to interchange the row numbers for the labels and column names of the data table for better user experience. Reason for same are listed in the discussion link above.

I would like to contribute a PR for your review if you agree to the premise. Thank you.

**Comment by shannonpileggi** [comment]
Thanks for following up, @vkatti! We agree that this would be a sensible change, a PR would be welcome.
